### ISSUE TITLE
Detect CPU features (such as SSE4) at runtime.

### ISSUE THREAD

**Issue by orlp** [BLAKE2/BLAKE2#1]
I suggest detecting CPU features for the SSE implementations at runtime rather than compile time using `cpuid`, because often, especially on Windows, one fat binary is distributed over many end-user machines.

This would work by creating multiple `blake2s_compress` and `blake2b_compress` functions, each with the apprioriate CPU features. Then once, at startup or at the first call, the correct function will be selected and stored in a function pointer (costing no branches during the actual time critical parts.)

The disadvantage of this is slightly larger code size in the binary, but __not the cache__. On the common user machines where this feature is wanted, the extra kilobyte(s) of binary space is well worth the optimum performance on every machine.

On very space-limited machines (embedded devices), this feature is not wanted and can be trivially disabled.

**Comment by xiegeo** [comment]
Any update on this?

**Comment by sneves** [comment]
This ended up being included in [libb2](https://blake2.net/libb2-0.96.tar.gz) (see `src/blake2-dispatch.c`), but was never moved to the reference code.
