### ISSUE TITLE
:if ??

### ISSUE THREAD

**Issue by janfrode** [BLAKE2/BLAKE2#11]
Looks to me like there's an erroneous ":" that's snuck into blake2sp-ref.c:

% make
cc blake2sp-ref.c blake2s-ref.c -o blake2sp -std=c99 -Wall -pedantic -DBLAKE2SP_SELFTEST
blake2sp-ref.c: In function ‘blake2sp’:
blake2sp-ref.c:191:3: error: expected expression before ‘:’ token
   :if ( NULL == in && inlen > 0 ) return -1;
   ^
make: *** [blake2sp] Error 1

**Comment by ivan** [comment]
Indeed, https://github.com/BLAKE2/BLAKE2/commit/a18d2b03fb0df1458c447d488816b51b1164c006#diff-2d58efb1034f0d5d99698facae807b66R191

**Comment by sneves** [comment]
Thanks, fixed.
