### ISSUE TITLE
Personalization misaligned in C#

### ISSUE THREAD

**Issue by Steppenwolfe65** [BLAKE2/BLAKE2#24]
Hi,
First off, thanks for the great work! 
I've been looking over the code from both submissions and I noticed that a personalization value is not being added to the correct position within Blake2IvBuilder::ConfigB method.
The second half of the input just overwrites the first half at the same position within the rawConfig array:

// Personalization
...
rawConfig[6] = Blake2BCore.BytesToUInt64(config.Personalization, 0);
rawConfig[6] = Blake2BCore.BytesToUInt64(config.Personalization, 8); // should start at 56 bytes [7]

**Comment by sneves** [comment]
You're right, thanks. Fixed in 9a57356.
