### ISSUE TITLE
Want to package for OS X Homebrew, but BLAKE2 does not tag any releases.

### ISSUE THREAD

**Issue by grempe** [BLAKE2/BLAKE2#26]
I noticed that the `b2sum` utility is not available in Homebrew on OS X.  If you are not familiar homebrew is a *very* popular way to distribute compiled from source packages for OS X for programs that are not included with the OS.

http://brew.sh/

I was surprised to find that there was no package for b2sum out of the thousands that they offer.

After submitting issue #25 I am able to cleanly compile b2sum on OS X using the built in dev tools so I wanted to create a homebrew `formula` (which is just a Ruby script that downloads, compares to a known hash, compiles and installs a binary).  This would be a relatively easy thing for me to do and would be useful to others.

However, one of the requirements of getting a package merged into Homebrew core is the ability to reference a release tarball or git tag.  Sadly I think I discovered why no-one has packaged up b2sum to date, because there are *no* releases or milestone tags in this repository!

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md

https://github.com/BLAKE2/BLAKE2/tags

Homebrew needs this so that they have a stable anchor tarball that can be hashed so that everyone who installs from that tarball is assured of getting what the packager intended.

If the project would cut a release, or tag the current head of the master branch, I would be able to complete this contribution. This is just a sound practice in any case.

Can you please cut a release, or even just an annotated tag, of the current state of the repository?  If so I will create that homebrew package.  There are no other actions that this project would need to take other than periodically tagging new releases (especially those with changes to b2sum).

**Comment by grempe** [comment]
As a follow up, I know there is a link to binaries here:

https://blake2.net/#su

But they are three years old and do not include an OS X compiled binary.

**Comment by sneves** [comment]
There's a `20160619` tag now.

**Comment by grempe** [comment]
I have created the homebrew formula and submitted a pull request to add it to homebrew-core.

https://github.com/Homebrew/homebrew-core/pull/2208

**Comment by grempe** [comment]
The `b2sum` command is now available for install, compiled from pristine source, in the homebrew package manager for OS X.

```
$ brew update
Updated Homebrew from b05a596 to 6dc72f2.
...
==> New Formulae
b2sum
...
```

You can install it now with a simple `brew install`.

Here is the commit, for those who may be interested, with the complete formula for install.

https://github.com/Homebrew/homebrew-core/commit/e016cda47dfa298c6628de3e9d0fd976eecd91be

Assuming no compilation changes, for future updates only a new tag is required from this project, and a pull request on that formula to update the tagged download URL and the sha1 of that new tarball.

I'll close this issue now that the process is complete.

Cheers!  I hope people enjoy!
