### ISSUE TITLE
memcpy of overlapping buffer in final

### ISSUE THREAD

**Issue by tiran** [BLAKE2/BLAKE2#32]
Coverity Scan complains about overlapping buffers in `blake2s_final()` and `blake2b_final()`.

```
346  if( S->buflen > BLAKE2S_BLOCKBYTES )
347  {
348    blake2s_increment_counter( S, BLAKE2S_BLOCKBYTES );
349    blake2s_compress( S, S->buf );
350    S->buflen -= BLAKE2S_BLOCKBYTES;
   CID 1372514 (#1 of 1): Overlapping buffer in memory copy (BUFFER_SIZE)4. overlapping_buffer: The source buffer &S->buf[BLAKE2S_BLOCKBYTES] potentially overlaps with the destination buffer S->buf, which results in undefined behavior for memcpy.
   Use memmove instead of memcpy.
351    memcpy( S->buf, S->buf + BLAKE2S_BLOCKBYTES, S->buflen );
352  }
```

**Comment by sneves** [comment]
This was privately reported to me a while ago, and the conclusion was that it was a false positive: overlap is not possible with legal usage of the blake2 API.

That being said, I don't like it either, and I have a more or less stable [branch](https://github.com/BLAKE2/BLAKE2/tree/cleanups) that resolves many of these small issues. I have been wanting to switch to it, but am afraid of breaking existing code that depends on the current `master`.

**Comment by sneves** [comment]
The merge of #34 completely solved/invalidated this issue, I think.
