### ISSUE TITLE
Please provide a reference implementation for ARM NEON

### ISSUE THREAD

**Issue by noloader** [BLAKE2/BLAKE2#38]
Hi Gentleman,

This is more a feature request than anything else. BLAKE2b is being cut-in on 32-bit ARM platforms based on code from @sneves and @veorq. The code is production quality, and its numbers are very good, and usually somewhere in the ballpark of a 3x speedup.

Here's are the numbers copied from a request for [Jack Llyod's Botan](https://github.com/randombit/botan/issues/845). The *"NEON implementation"* is a modified version of BLAKE2's intrinsic implementation for ARM.

> ... The dev-boards used for testing were a BeagleBoard v3 (Cortex-A8), Banana Pi (Cortex-A7) and CubieTruck v5 (Cortex-A7). The BeagleBoard was configured with `-march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard`; and the CubieTruck was configured with `-march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard`.
> 
> Here are the relative numbers:
> 
> * BeagleBoard, CXX implementation (0.95 GiHz)
>  
> ```
> $ ./botan speed --msec=3000 Blake2b
> Blake2b(512) [base] hash 11.721 MiB/sec (35.164 MiB in 3000.092 ms)
> ```
> 
> * BeagleBoard, NEON implementation (0.95 GiHz)
>  
> ```
> $ ./botan speed --msec=3000 Blake2b
> Blake2b(512) [base] hash 31.662 MiB/sec (94.988 MiB in 3000.038 ms)
> ```
> 
> * BananaPi, CXX implementation (0.96 GiHz)
>  
> ```
> $ ./botan speed --msec=3000 Blake2b
> Blake2b(512) [base] hash 15.769 MiB/sec (47.309 MiB in 3000.182 ms)
> ```
> 
> * BananaPi, NEON implementation (0.96 GiHz)
>  
> ```
> $ ./botan speed --msec=3000 Blake2b
> Blake2b(512) [base] hash 41.872 MiB/sec (125.617 MiB in 3000.044 ms)
> ```
> 
> * CubieTruck, CXX implementation (1.7 GiHz)
>  
> ```
> $ ./botan speed --msec=3000 Blake2b
> Blake2b(512) [base] hash 27.119 MiB/sec (81.359 MiB in 3000.123 ms)
> ```
> 
> * CubieTruck, NEON implementation (1.7 GiHz)
>  
> ```
> $ ./botan speed --msec=3000 Blake2b
> Blake2b(512) [base] hash 70.449 MiB/sec (211.348 MiB in 3000.020 ms)
> ```

**Comment by sailnfool** [comment]
Finally figured out further changes to the makefile to incorporate the existing NEON code for b2sum.  You can find my version of the b2sum makefile with further changes at:
[b2sumARM](https://github.com/sailnfool/b2sumARM)
