### ISSUE TITLE
Feature request: Add -c argument to b2sum

### ISSUE THREAD

**Issue by trumpet205** [BLAKE2/BLAKE2#39]
Take md5sum for instance where you can save the results to a text file and use -c argument to recheck the hashes. This simplifies the task of verifying file integrities, especially when dealing with large number of files and folders.

Kindly request you add this feature to b2sum. It should,

1. Behave like -c argument in md5sum, sha1sum, etc.
2. Support subdirectory scan.
3. Able to auto detect UTF-8 characters in file and folder names. This is important since saved text file probably won't have BOM header.

**Comment by zooko** [comment]
Please check whether the coreutils b2sum tool provides this: https://www.gnu.org/software/coreutils/manual/html_node/b2sum-invocation.html If so, then maybe we should recommend that people use that instead? I'm not opposed to this feature, but I'm not going to have the time to implement and maintain it myself, so it would be up to someone else if we're going to support it in this codebase.

**Comment by trumpet205** [comment]
I probably have to compile coreutils myself since Raspbian (only Linux distro I can use readily) doesn't have b2sum in its coreutils.

I did take a quick look at the commit about added b2sum in coreutils,
http://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=ea94589e9ef02624a3837f97f80efd7d3dcf56bf

Maybe tests/misc/b2sum.sh is what gave b2sum the ability to use -c argument? Because b2sum.c is pretty much an identical copy of the one hosted here. I'm no programmer by any means.

**Comment by trumpet205** [comment]
Went ahead and compiled coreutils on a Linux virtual session. b2sum in coreutils does have -c argument. Haven't tested the subdirectory scan or unicode characters but it should support it, given md5sum does.

One thing though, it only supports Blake2b. So no luck if you want to use other flavors of Blake2. In addition for most Linux distributions their coreutils don't have b2sum so you have to download the source and compile the whole thing just to get this particular b2sum.

I believe it still be of use for this feature to be added to reference b2sum.

**Comment by sneves** [comment]
It's not gonna happen soon, unless there's a good PR introducing this functionality.

**Comment by zooko** [comment]
If you want to use the other flavors of BLAKE2, please submit a feature request to coreutils to add it. I would be happy to help if the coreutils devs want to support that feature request. As for the packaging issue, in a few months/years all Linux distributions will come with a newer release of coreutils that includes b2sum.
