### ISSUE TITLE
Porting on SPARC CPU

### ISSUE THREAD

**Issue by marcofortina** [BLAKE2/BLAKE2#46]
Hello there,
is it possible to have a porting on SPARC CPU?

Here the cpucaps:
lush,stbar,swap,muldiv,v9,blkinit,n2,mul32,div32,fsmuld,v8plus,popc,vis,vis2,ASIBlkInit,fmaf,vis3,hpc,ima,pause,cbcond,adp,vis3b,pause-nsec,mwait,sparc5,vamask,aes,des,camellia,md5,sha1,sha256,sha512,mpmul,montmul,montsqr,crc32c,xmpmul,xmontmul,xmontsqr
Thanks,
Marco

**Comment by sneves** [comment]
The reference implementation in the `ref/` directory is architecture-agnostic. Maybe you are using the `sse/` code, which is not?

**Comment by marcofortina** [comment]
yes I know. Do you have any plan to have an optimized code like sse2 for sparc cpu?

**Comment by sneves** [comment]
No. I'm neither familiar with the architecture, nor do I have access to it.
