### ISSUE TITLE
Any plan to make a new release?

### ISSUE THREAD

**Issue by sunpoet** [BLAKE2/BLAKE2#60]
Hi,

Is there any plan to make a new release, e.g. 20190724?
Thanks.

**Comment by noloader** [comment]
Yeah, + 1.

There a lot of drift between the last release from 2016 and current sources.

**Comment by sneves** [comment]
Tagged current master as `20190724`.

**Comment by sunpoet** [comment]
Thanks!

**Comment by noloader** [comment]
Superb, thanks man!

**Comment by noloader** [comment]
@sneves,

This is really nice. It has the Neon gear, too. What a pleasant surprise.

Give me a few minutes to update [PR 63](https://github.com/BLAKE2/BLAKE2/pull/63).
