### ISSUE TITLE
Support for Apple Silicon on macOS (mach-o ARM64)

### ISSUE THREAD

**Issue by johnalanwoods** [BLAKE2/BLAKE2#70]
Can you look to support M1/Apple Silicon?

**Comment by sneves** [comment]
I have no Apple hardware, and no particular interest in supporting it. I would not turn down someone else's contributions in this direction.

Given how wide the M1 microarchitecture is supposed to be, I would expect the C code to do pretty well on its own, without any particular optimizations. Low-latency NEON may help, but that would depend on undocumented information about the chip.

**Comment by johnalanwoods** [comment]
@sneves - any idea the build flags I can use to try and build on ARM?

Currently getting this from compiler:

`error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size`

**Comment by ghost** [comment]
FWIW, I'm able to compile using gcc and run in macos M1 arm instances of github actions. In [this repo](https://github.com/npy0/nanopy/blob/main/.github/workflows/nanopy.yml)
