### ISSUE TITLE
Question: Where do IV values come from?

### ISSUE THREAD

**Issue by phantomcraft** [BLAKE2/BLAKE2#80]
There are values called IVs used by Blake and I want to know more about them:

```
static const uint64_t blake2b_IV[8] =
{
  0x6a09e667f3bcc908ULL, 0xbb67ae8584caa73bULL,
  0x3c6ef372fe94f82bULL, 0xa54ff53a5f1d36f1ULL,
  0x510e527fade682d1ULL, 0x9b05688c2b3e6c1fULL,
  0x1f83d9abfb41bd6bULL, 0x5be0cd19137e2179ULL
};
```

```
static const uint32_t blake2s_IV[8] =
{
  0x6A09E667UL, 0xBB67AE85UL, 0x3C6EF372UL, 0xA54FF53AUL,
  0x510E527FUL, 0x9B05688CUL, 0x1F83D9ABUL, 0x5BE0CD19UL
};
```

What was the criterion/method used to establish them?

If I change them and use random values, will this compromise the security of Blake2?

**Comment by noloader** [comment]
[BLAKE2: simpler, smaller, fast as MD5](https://www.blake2.net/blake2.pdf).

**Comment by sneves** [comment]
The IV constants are the same as the ones from SHA-256 and SHA-512, respectively, which are obtained from the [square roots of the first 8 primes](https://en.wikipedia.org/wiki/SHA-2#Pseudocode). In BLAKE2, the IV constants are also used within the compression function to prevent the permutation from entering symmetric states. To this end, the only real constraint that those constants have is that they should be distinct from each other.

**Comment by phantomcraft** [comment]
@sneves 

Thanks.
